import { describe, it, expect } from "vitest";
import { ExpressRouteEmitter } from "./ExpressRouteEmitter";
import { TandemIR, IRIntent, createEmptyIR } from "@tandem-lang/compiler";
import type { GeneratedCode } from "../interfaces/ICodeEmitter";
import {
  MockProvider,
  CodeGenerationPipeline,
  IRContextBuilder,
} from "@tandem-lang/llm";

function createTestIR(
  intents: Array<{ fqn: string; intent: IRIntent }>
): TandemIR {
  const ir = createEmptyIR();

  for (const { fqn, intent } of intents) {
    ir.intents.set(fqn, intent);
  }

  return ir;
}

function createMockPipeline(): CodeGenerationPipeline {
  const provider = new MockProvider({ apiKey: "mock-key", model: "mock-model" });
  provider.setMockResponse({
    implementation: 'res.json({ message: "Generated by mock" });',
    validation: "",
    imports: [],
  });
  const contextBuilder = new IRContextBuilder();
  return new CodeGenerationPipeline(provider, contextBuilder, { maxRetries: 1 });
}

describe("ExpressRouteEmitter", () => {
  describe("modular output", () => {
    it("emits handlers and routes to module directories", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: {
              fields: [{ name: "id", type: { kind: "simple", fqn: "String" } }],
            },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
        {
          fqn: "api.tasks.ListTasks",
          intent: {
            kind: "route",
            name: "api.tasks.ListTasks",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const filenames = files.map((f: GeneratedCode) => f.filename);

      expect(filenames).toContain("api/users/handlers.ts");
      expect(filenames).toContain("api/users/routes.ts");
      expect(filenames).toContain("api/tasks/handlers.ts");
      expect(filenames).toContain("api/tasks/routes.ts");
      expect(filenames).toContain("routes/index.ts"); // Aggregate
    });

    it("imports types from local types.ts in handlers", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: {
              fields: [{ name: "id", type: { kind: "simple", fqn: "String" } }],
            },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const handlersFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/handlers.ts"
      );
      expect(handlersFile).toBeDefined();
      expect(handlersFile!.content).toContain('from "./types"');
      expect(handlersFile!.content).toContain("GetUserInput");
      expect(handlersFile!.content).toContain("GetUserOutput");
    });

    it("imports handlers from local handlers.ts in routes", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const routesFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/routes.ts"
      );
      expect(routesFile).toBeDefined();
      expect(routesFile!.content).toContain('from "./handlers"');
      expect(routesFile!.content).toContain("getUserHandler");
    });

    it("generates aggregate router that combines all modules", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
        {
          fqn: "api.tasks.ListTasks",
          intent: {
            kind: "route",
            name: "api.tasks.ListTasks",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const aggregate = files.find((f: GeneratedCode) => f.filename === "routes/index.ts");
      expect(aggregate).toBeDefined();
      expect(aggregate!.content).toContain("api/users/routes");
      expect(aggregate!.content).toContain("api/tasks/routes");
      expect(aggregate!.content).toContain("apiUsersRouter");
      expect(aggregate!.content).toContain("apiTasksRouter");
      expect(aggregate!.content).toContain('router.use("/api/users"');
      expect(aggregate!.content).toContain('router.use("/api/tasks"');
    });

    it("returns empty array for IR with no intents", async () => {
      const ir = createEmptyIR();

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      expect(files).toHaveLength(0);
    });
  });

  describe("handler generation", () => {
    it("generates GET handler with query input", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: {
              fields: [{ name: "id", type: { kind: "simple", fqn: "String" } }],
            },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const handlersFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/handlers.ts"
      );
      expect(handlersFile!.content).toContain("req.query");
      expect(handlersFile!.content).toContain("getUserHandler");
    });

    it("generates POST handler with body input", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.CreateUser",
          intent: {
            kind: "route",
            name: "api.users.CreateUser",
            inputType: {
              fields: [
                { name: "name", type: { kind: "simple", fqn: "String" } },
              ],
            },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const handlersFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/handlers.ts"
      );
      expect(handlersFile!.content).toContain("req.body");
    });

    it("includes JSDoc from spec", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
            spec: "Retrieves a user by ID",
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const handlersFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/handlers.ts"
      );
      expect(handlersFile!.content).toContain("* Retrieves a user by ID");
    });
  });

  describe("route generation", () => {
    it("generates correct route path", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUserById",
          intent: {
            kind: "route",
            name: "api.users.GetUserById",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const routesFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/routes.ts"
      );
      expect(routesFile!.content).toContain('router.get("/getUserById"');
    });

    it("uses correct HTTP method based on intent name", async () => {
      const ir = createTestIR([
        {
          fqn: "api.users.GetUser",
          intent: {
            kind: "route",
            name: "api.users.GetUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
        {
          fqn: "api.users.CreateUser",
          intent: {
            kind: "route",
            name: "api.users.CreateUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
        {
          fqn: "api.users.UpdateUser",
          intent: {
            kind: "route",
            name: "api.users.UpdateUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
        {
          fqn: "api.users.DeleteUser",
          intent: {
            kind: "route",
            name: "api.users.DeleteUser",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const routesFile = files.find(
        (f: GeneratedCode) => f.filename === "api/users/routes.ts"
      );
      expect(routesFile!.content).toContain("router.get");
      expect(routesFile!.content).toContain("router.post");
      expect(routesFile!.content).toContain("router.put");
      expect(routesFile!.content).toContain("router.delete");
    });
  });

  describe("module aliasing", () => {
    it("creates valid JavaScript identifiers for module aliases", async () => {
      const ir = createTestIR([
        {
          fqn: "deep.nested.module.GetItem",
          intent: {
            kind: "route",
            name: "deep.nested.module.GetItem",
            inputType: { fields: [] },
            outputType: { kind: "simple", fqn: "String" },
          },
        },
      ]);

      const emitter = new ExpressRouteEmitter({ pipeline: createMockPipeline() });
      const files = await emitter.emit(ir);

      const aggregate = files.find((f: GeneratedCode) => f.filename === "routes/index.ts");
      expect(aggregate!.content).toContain("deepNestedModuleRouter");
      expect(aggregate!.content).toContain('router.use("/deep/nested/module"');
    });
  });
});
