import { describe, it, expect } from "vitest";
import {
  generateBarrel,
  generateDirectoryBarrel,
  generateModuleBarrel,
  generateAggregateBarrel,
  BarrelExport,
} from "./barrelGenerator";

describe("generateBarrel", () => {
  it("generates empty barrel for no exports", () => {
    const result = generateBarrel([]);
    expect(result).toContain("export {};");
  });

  it("generates re-export all statement", () => {
    const exports: BarrelExport[] = [{ name: "*", from: "./types" }];
    const result = generateBarrel(exports);

    expect(result).toContain('export * from "./types";');
  });

  it("generates named export statement", () => {
    const exports: BarrelExport[] = [{ name: "User", from: "./user" }];
    const result = generateBarrel(exports);

    expect(result).toContain('export { User } from "./user";');
  });

  it("generates type-only export", () => {
    const exports: BarrelExport[] = [
      { name: "User", from: "./user", isType: true },
    ];
    const result = generateBarrel(exports);

    expect(result).toContain('export type { User } from "./user";');
  });

  it("generates aliased export", () => {
    const exports: BarrelExport[] = [
      { name: "User", from: "./user", alias: "UserType" },
    ];
    const result = generateBarrel(exports);

    expect(result).toContain('export { User as UserType } from "./user";');
  });

  it("generates multiple exports", () => {
    const exports: BarrelExport[] = [
      { name: "*", from: "./types" },
      { name: "api", from: "./client" },
    ];
    const result = generateBarrel(exports);

    expect(result).toContain('export * from "./types";');
    expect(result).toContain('export { api } from "./client";');
  });

  it("includes header comment", () => {
    const result = generateBarrel([]);
    expect(result).toContain("Generated by Tandem");
  });
});

describe("generateDirectoryBarrel", () => {
  it("generates re-exports for subdirectories", () => {
    const result = generateDirectoryBarrel(["users", "tasks"]);

    expect(result).toContain('export * from "./users";');
    expect(result).toContain('export * from "./tasks";');
  });

  it("generates type-only re-exports", () => {
    const result = generateDirectoryBarrel(["users"], true);

    expect(result).toContain('export type * from "./users";');
  });

  it("handles empty subdirs", () => {
    const result = generateDirectoryBarrel([]);
    expect(result).toContain("export {};");
  });
});

describe("generateModuleBarrel", () => {
  it("generates exports from file map", () => {
    const files = new Map([
      ["User", "./user"],
      ["Task", "./task"],
    ]);
    const result = generateModuleBarrel(files);

    expect(result).toContain('export { User } from "./user";');
    expect(result).toContain('export { Task } from "./task";');
  });

  it("generates type-only exports", () => {
    const files = new Map([["User", "./user"]]);
    const result = generateModuleBarrel(files, true);

    expect(result).toContain('export type { User } from "./user";');
  });
});

describe("generateAggregateBarrel", () => {
  it("generates re-exports from multiple modules", () => {
    const moduleExports = new Map([
      ["api/users", ["User", "UserId"]],
      ["domain/tasks", ["Task"]],
    ]);
    const result = generateAggregateBarrel(moduleExports);

    expect(result).toContain('export { User, UserId } from "./api/users";');
    expect(result).toContain('export { Task } from "./domain/tasks";');
  });

  it("sorts module paths", () => {
    const moduleExports = new Map([
      ["z/module", ["Z"]],
      ["a/module", ["A"]],
    ]);
    const result = generateAggregateBarrel(moduleExports);

    const aIndex = result.indexOf("a/module");
    const zIndex = result.indexOf("z/module");
    expect(aIndex).toBeLessThan(zIndex);
  });

  it("sorts export names", () => {
    const moduleExports = new Map([["module", ["Zebra", "Apple"]]]);
    const result = generateAggregateBarrel(moduleExports);

    expect(result).toContain("{ Apple, Zebra }");
  });

  it("generates type-only exports", () => {
    const moduleExports = new Map([["api/users", ["User"]]]);
    const result = generateAggregateBarrel(moduleExports, true);

    expect(result).toContain('export type { User } from "./api/users";');
  });

  it("includes aggregate comment", () => {
    const moduleExports = new Map([["api/users", ["User"]]]);
    const result = generateAggregateBarrel(moduleExports);

    expect(result).toContain("Aggregate re-exports");
  });

  it("skips modules with no exports", () => {
    const moduleExports = new Map([
      ["api/users", ["User"]],
      ["empty/module", []],
    ]);
    const result = generateAggregateBarrel(moduleExports);

    expect(result).not.toContain("empty/module");
  });
});
